# https://docs.travis-ci.com/user/ci-environment/#Virtualization-environments
dist: trusty

language: java

jdk:
  - oraclejdk11

services:
  - rabbitmq

cache:
  directories:
  - $HOME/.m2

  # Override default travis to use the maven wrapper
install: ./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
script: ./mvnw clean verify -B

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/637e968b45032d16ee26
    on_success: change
    on_failure: always
